Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -18,6 +18,7 @@ jobs:
             key: ${{ runner.os }}-sonar
             restore-keys: ${{ runner.os }}-sonar
       - name: Run Codescan On Push
+        continue-on-error: true
         if: github.event_name == 'push'
         uses: codescan-io/codescan-scanner-action@1.3
         with:
@@ -27,6 +28,7 @@ jobs:
           args: |
             sonar.host.url=https://staging.codescan.io
       - name: Run Codescan On PR
+        continue-on-error: true
         if: github.event_name == 'pull_request'
         uses: codescan-io/codescan-scanner-action@1.3
         with:
@@ -38,3 +40,18 @@ jobs:
             sonar.pullrequest.base=${{github.base_ref}}
             sonar.pullrequest.key=${{github.event.number}}
             sonar.host.url=https://staging.codescan.io
+      - name: Quality Gate Check
+        if: github.event_name == 'pull_request'
+        continue-on-error: true
+        env:
+          TOKEN: ${{ secrets.staging_token }}
+          PR_KEY: ${{github.event.number}}
+          PROJECT_KEY: CodeScanDemo
+        run: |
+          echo  $(curl -s -u "$TOKEN": "https://XXXXXXXXX.com/api/qualitygates/project_status?projectKey=$PROJECT_KEY&pullRequest=$PR_KEY")
+          qg_status=$(curl -s -u "$TOKEN": "https://XXXXXXX.com/api/qualitygates/project_status?projectKey=$PROJECT_KEY&pullRequest=$PR_KEY" | jq -r '.projectStatus.status')
+          echo "QG Script --> Quality Gate status is ${qg_status}"
+          if [ "${qg_status}" != "OK" ]; then
+            echo "QG Script --> Quality gate is not OK - exiting with error"
+            exit 1
+            fi
